# Generated by Django 3.2.18 on 2023-06-15 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_feed_image'),
        ('content', '0020_alert_reply_content'),
    ]

    operations = [
    ]
